# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
CLOUDINARY_URL: 'cloudinary://195583184244595:WbMJ92G3_tCb-Rmy-9hBQqKRVv4@liliangdo'

development:

  FB_ID: '640095192826773'
  FB_SECRET: 'fb632c5f29bab2969baa43602be3c55f'

production:
  FB_ID: '640093272826965'
  FB_SECRET: 3aee1b8794322477b5d39f2c37b725fa
